### ISSUE TITLE
Issue with installation{ PartError, parse_error: invalid syntax}

### ISSUE THREAD

**Issue by gbernal** [rienafairefr/python-ldraw#8]
Hi There, 

Thank you for sharing this library. I'm hoping that you can help me. 
I tried installing the library via pip but I get the error below when I import the library or try running one of the examples provided by this repo.

My OS is Mac 10.15.7

Any help is appreciated.

Thanks!
```
Traceback (most recent call last):
  File "/Users/guillermobernal/PycharmProjects/LegoLDRAW/test.py", line 1, in <module>
    import ldraw
  File "/Users/guillermobernal/miniconda3/envs/LegoLDRAW/lib/python3.7/site-packages/ldraw/__init__.py", line 28, in <module>
    from ldraw.library_gen import library_gen_main
  File "/Users/guillermobernal/miniconda3/envs/LegoLDRAW/lib/python3.7/site-packages/ldraw/library_gen.py", line 8, in <module>
    from ldraw.generation.parts import gen_parts
  File "/Users/guillermobernal/miniconda3/envs/LegoLDRAW/lib/python3.7/site-packages/ldraw/generation/parts.py", line 15, in <module>
    from ldraw.parts import PartError
  File "/Users/guillermobernal/miniconda3/envs/LegoLDRAW/lib/python3.7/site-packages/ldraw/parts.py", line 383
    except PartError, parse_error:
                    ^
SyntaxError: invalid syntax

```

**Comment by gbernal** [comment]
This issue was resolved by cloning the repo and running python setup.py install in the root directory
